[versions]
compose_version = "1.8.0"
kotlin = "2.2.0"
agp = "8.13.0"
ksp = "2.2.0-2.0.2"
nav = "2.9.0"
room = "2.7.0"
lifecycle = "2.9.0"
material3 = "1.3.1"
junit = "4.13.2"
coil3 = "3.3.0"
datastore = "1.1.1"

[libraries]
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "nav" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.16.0" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.10.0" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose_version" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose_version" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-database-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# OkHttp

squareup-okhttp3-bom = { module = "com.squareup.okhttp3:okhttp-bom", version = "5.2.1" }
squareup-okhttp3 = { module = "com.squareup.okhttp3:okhttp" }
squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:okhttp" }
jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.9.0" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }

coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil3" }

# Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "room" }
androidx-room-rxjava3 = { module = "androidx.room:room-rxjava3", version.ref = "room" }
androidx-room-guava = { module = "androidx.room:room-guava", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }


junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext = { module = "androidx.test.ext:junit", version = "1.3.0" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.7.0" }
#androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose_version" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose_version" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose_version" }


[plugins]
jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
